### ISSUE TITLE
Problem with UTF-16 XML encoding

### ISSUE THREAD

**Issue by guillermo-jimenez** [sixlettervariables/sierra-ecg-tools#20]
Hi! 

First of all, thanks for this, you have really saved me a ton of time.

I'm not completely sure this will updated, as it's a fairly old library, but I've been trying to use this with some 1.04 files that employed utf-16 encoding instead of the utf-8 given as an example. The `sierraEcg.readFile` function was returning error due to the way `fs` is reading the file as a buffer. The fix is as simple as adding an option to the `readFile` function in `index.js` to specify the file encoding, defaulting to utf-8:

```
function readFile(filename, cb, encoding='utf-8') {
  var ext = path.extname(filename).toLowerCase();
  switch (ext) {
    case '.xml':
      break;
    default:
      throw new Error('Unsupported file type');
  }

  var deferred = fs.readFileAsync(filename, encoding)
    .then(parseXml)
    .then(sierraEcg.parseXml)
    .then(sierraEcg.decodeXli)
    .then(sierraEcg.updateLeads)
    .then(sierraEcg.createObjects);

  return deferred.nodeify(cb);
}
```

Then, using e.g. 'ucs2' as an encoding would allow a correct file parsing.

Thanks again!
Guille

**Comment by sixlettervariables** [comment]
Let me know if this would work as well: https://github.com/sixlettervariables/sierra-ecg-tools/pull/21

For curiosity's sake, could you reach out to me via email (in the README) regarding how you're using the toolset? I believe you would be the first using this from NodeJS.

**Comment by guillermo-jimenez** [comment]
It works! Thanks a lot. 

Sure, I'll fill you in about the project via email :+1:
