### ISSUE TITLE
Support for PhilipsECG 1.04.02

### ISSUE THREAD

**Issue by tecamenz** [sixlettervariables/sierra-ecg-tools#47]
Hi 

I try to read ECG data with the PhilipsECG 1.04.02 format (which is not officially supported by your library). 
Reading works fine but I get a warning like this:
`/home/jovyan/projects/sierraecg/xli.py:42: RuntimeWarning: overflow encountered in short_scalars
  z = (y + y) - x - last`

I can still plot the data and it looks fine but I wanted to ask if the data is still valid?

Kind regards

**Comment by sixlettervariables** [comment]
Could you email an anonymized ECG for me to take a look at? `christopher.watford@gmail.com`

Sounds like the `y` value (though that's a guess).

**Comment by sixlettervariables** [comment]
I believe I have a fix and released it for you to try out at `v0.2.1`: https://pypi.org/project/sierraecg/0.2.1/

**Comment by tecamenz** [comment]
Hi, sorry for the late reply. Was on a break. Didn't thought I get a reply so fast! 
Version 0.2.1 fixed the issue for me. Thanks a lot !

**Comment by sixlettervariables** [comment]
Glad I could help!
